Resolve #299
cbeleites/hyperSpec pull request #318
Opened 2021-04-14 17:32 UTC by sangttruong

In the development version of hyperSpec, I found 3 functions/objects that define color palettes.
Based on the suggestions, I rename all palette objects (prefix palette_)

Resolve #299

2021-04-14 23:04 UTC, GegznaV requested changes
1) If user-visible changes are introduced, they must be properly described in the `NEWS.md` file. Did you read `CONTRIBUTION.md`?
2) Please avoid committing files that are not related to the issue. I mean `hyperSpec_0.100.0.zip` this time. Please, remove this file and do not include it in the future.
3) Some tests do not pass on the old release of R (v.3.6). I'm not sure what is the reason. 
4) There are 3 renamed functions, so it would have been better if there were 3 separate commits (you will not fix this now, but adhere to this guideline in the future).
5) The short commit messages should be self-explanatory, Not, e.g., "Resolve #299", but e.g., "Rename function: matlab.palette() → palette_matlab()" (you will not fix it now, but keep that in mind for the future).

2021-05-10 16:03 UTC, bryanhanson reviewed
Regarding the unit tests in `palette_matlab.R` my own opinion is that testing this sort of thing is unnecessary.  Either the palettes exist, or they don't.  The tests in this PR verify that one entry in the palette is the expected one, but I can't imagine a situation where this would change, so I'm not really sure what we are trying to defend against.  If it were up to me I'd simply remove the unit tests for this function.

2021-05-27 22:27 UTC, GegznaV requested changes
There is some general feedback on unit tests.

2021-05-27 22:27 UTC, GegznaV commented on hyperSpec/R/palette_matlab.R
> +library(hySpc.testthat)
Function `library()` must not be used in packages.

2021-05-27 22:27 UTC, GegznaV commented on hyperSpec/R/palette_matlab.R
> +  test_that("test palette matlab dark color", {
The whole line should be as a fluent and logical sentence, e.g., 
"Test that *palette_matlab_dark() generates correct colors*"
"Test that *palette_matlab_dark() generates works*"
etc.
This sentence should describee the unit of functionality that is tested by the unit test.

2021-05-27 22:27 UTC, GegznaV commented on hyperSpec/R/palette_matlab.R
> +  test_that("test palette alois", {
The whole line should be as a fluent and logical sentence.

2021-05-27 22:27 UTC, GegznaV commented on hyperSpec/R/palette_matlab.R
> +  test_that("test palette matlab", {
The whole line should be as a fluent and logical sentence

2021-05-27 22:27 UTC, GegznaV commented on hyperSpec/R/palette_matlab.R
> +hySpc.testthat::test(palette_matlab) <- function() {
Tests should go in the same order as functions (matlab, matlab dark, alois)

2021-05-27 22:31 UTC, GegznaV commented
@bryanhanson:
> Either the palettes exist, or they don't. 

Some palettes depand on other functions of "R". And, e.g., in version 4.0 "R" changed some default colors.

2021-06-21 07:53 UTC, GegznaV requested changes
Please, add a new line at the end of files, where needed.

2021-06-21 07:53 UTC, GegznaV commented on hyperSpec/R/palette_matlab.R
> +}
Please, leave a blank line at the end of each file. In some circumstances, the absence of a new line may result in unwanted issues.

![image](https://user-images.githubusercontent.com/12725868/122726426-a7ed6f80-d27e-11eb-8665-5ecba5d13428.png)

2021-06-25 14:01 UTC, bryanhanson approved these changes

2021-06-25 14:02 UTC, merged